### ISSUE TITLE
ConfigParser 模块名字变化，引起 ImportError

### ISSUE THREAD

**Issue by TainKung** [JinnLynn/genpac#12]
Fedora 24, Python 3.5.1, pip 8.1.2，安装得到的 ConfigParser 为**全小写名字**。
```python
// 原来的
from ConfigParser import ConfigParser
// 应当改为下面语句
from configparser import ConfigParser
```
否则会报 No module named 'ConfigParser' 错误。
```
Traceback (most recent call last):
  File "/usr/bin/genpac", line 9, in <module>
    load_entry_point('genpac==1.4.1', 'console_scripts', 'genpac')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/genpac/__init__.py", line 4, in <module>
    from .core import main
  File "/usr/lib/python3.5/site-packages/genpac/core.py", line 7, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'
```

**Comment by TainKung** [comment]
问题已经解决。我错误地将 genpac 安装至 python3 中。用 pip2 重新安装后正常。
