### ISSUE TITLE
python3.5 import error

### ISSUE THREAD

**Issue by Novite5** [JinnLynn/genpac#13]
`Traceback (most recent call last):
  File "/usr/local/bin/genpac", line 7, in <module>
    from genpac import main
  File "/usr/local/lib/python3.5/dist-packages/genpac/__init__.py", line 4, in <module>
    from .core import main
  File "/usr/local/lib/python3.5/dist-packages/genpac/core.py", line 7, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'`

**Comment by JinnLynn** [comment]
genpac DOES NOT support python3 yet.
