### ISSUE TITLE
sudo genpac --gfwlist-url 报错

### ISSUE THREAD

**Issue by lkqin** [JinnLynn/genpac#6]
sudo genpac --gfwlist-url=https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Traceback (most recent call last):
  File "/usr/local/bin/genpac", line 9, in <module>
    load_entry_point('genpac==1.3.1', 'console_scripts', 'genpac')()
  File "/Users/LK/Desktop/src/genpac/genpac/core.py", line 420, in main
    generate()
  File "/Users/LK/Desktop/src/genpac/genpac/core.py", line 403, in generate
    '__RULES__': rules})
  File "/Users/LK/Desktop/src/genpac/genpac/core.py", line 63, in replace
    content = content.replace(k, v)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by JinnLynn** [comment]
出现错误的原因是你没有指定PAC文件所必须的代理信息。

现已加入对代理信息的检查， ca36ea88e7d963c5e3938b937d667103e6ac3742
